wandb_version: 1

out_noise:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702759814.857768
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
